# -*- coding: utf-8 -*-
"""NaiveBayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AjzclLEA4J3ooXYgZiN7KlogDoPIJ74m
"""

from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
import pandas as pd
import pandas as pd
from google.colab import files
uploaded = files.upload()
diabetes_data=pd.read_csv('pima-indians-diabetes-1.csv')


print ("Dataset: ",diabetes_data.head())
X=diabetes_data.loc[:,diabetes_data.columns!='class']
y=diabetes_data.loc[:,diabetes_data.columns=='class']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
columns=X_train.columns

model=GaussianNB()
model.fit(X_train,y_train)
pred = model.predict(X_test)

model_score = model.score(X_test, y_test)
print('Model score :',model_score)
print('Confusion Matrix:\n', metrics.confusion_matrix(y_test,pred))

print('Accuracy :',metrics.accuracy_score(y_test,pred))
print('Precision :',metrics.precision_score(y_test,pred))
print('Recall :',metrics.recall_score(y_test,pred))
print('F-score :',metrics.f1_score(y_test,pred))